name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]

    steps:
      - name: Setup MSVC
        if: matrix.os == 'windows-2022'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: 14.29
          arch: x64
          sdk: 10.0.19041.0

      - name: Checkout LibreSSL
        uses: actions/checkout@v6
        with:
          repository: PowerShell/LibreSSL
          ref: refs/tags/V4.0.0.0
          path: libressl

      - name: Build LibreSSL
        shell: pwsh
        working-directory: libressl
        run: |
          $installPrefix = "${{ github.workspace }}\libressl-install"
          cmake -S . -B build_nmake -G "NMake Makefiles" -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX="$installPrefix"
          cmake --build build_nmake
          cmake --install build_nmake
          tree "$installPrefix"

      - name: Archive LibreSSL
        uses: actions/upload-artifact@v5
        with:
          name: openssh-${{ runner.os }}
          path: |
            ${{ github.workspace }}/libressl-install

      - name: Checkout Self
        uses: actions/checkout@v6

      - name: Checkout OpenSSH
        uses: actions/checkout@v6
        with:
          repository: PowerShell/openssh-portable
          ref: refs/tags/v9.8.3.0
          path: openssh-portable

      - name: Modify with log
        shell: pwsh
        run: |
          7z x spectre.7z -o"$env:VCToolsInstallDir\lib"
          $env:LIBPATH = "$env:VCToolsInstallDir\lib\spectre\x64;" + $env:LIBPATH

      - name: Build
        shell: pwsh
        working-directory: ./openssh-portable/contrib/win32/openssh
        run: |
          msbuild Win32-OpenSSH.sln `
            /nologo `
            /t:Rebuild `
            /p:Platform=x64 `
            /p:Configuration=Release `
            /p:WindowsTargetPlatformVersion=10.0.19041.0 `
            /p:PlatformToolset=v142 `
            /p:WholeProgramOptimization=true `
            /p:Optimization=MinSpace `
            /p:FunctionLevelLinking=true

      - name: Archive OpenSSH
        uses: actions/upload-artifact@v5
        with:
          name: openssh-${{ runner.os }}
          path: |
            openssh-portable/bin/x64/Release/*.dll
            openssh-portable/bin/x64/Release/*.exe
